<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class MotorBikeFilterRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\Rule|array|string>
     */
    public function rules(): array
    {
        return [
            'color' => "max:20"
        ];
    }
    public function messages()
    {
        //I don't need customized in this business layer
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
