<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UserLogin extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\Rule|array|string>
     */
    public function rules(): array
    {
        return [
            "email" => "email|required",
            "password" => "required|min:3|max:20"
        ];
    }
    public function messages()
    {
        //In this case I don't need any customization
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
